manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: HNH-NASA
      url-base: https://github.com/HNH-NASA
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: HNH-NASA
      revision: main
  self:
    path: config
